name:  Build_POC

on: 
  workflow_dispatch:
  
jobs:

  Pre-Release:
  
    name: Versioning
    runs-on: ubuntu-latest
    
      
    steps:
      - uses: actions/checkout@v2
        
      - id: versnid
        run: |
          echo setting release version!!
          input='${{ github.workspace }}/version.cfg'
          echo "${{ github.run_number }}" >> version.cfg
          newversion=$(cat version.cfg)
          echo $newversion
          
