name:  Build_POC

on: 
  workflow_dispatch:
  
jobs:

  Pre-Release:
  
    name: Versioning
    runs-on: ubuntu-latest
    
      
    steps:
      - uses: actions/checkout@v2
        
      - id: versnid
        run: |
          echo setting release version!!
          echo "${{ github.run_number }}" >> version.cfg
          newversion=$(cat version.cfg | tr -d "[:space:]")
          echo $newversion
          
