name:  Build_POC

on: 
  workflow_dispatch:
  
jobs:

  Pre-Release:
  
    name: Versioning
    runs-on: ubuntu-latest
    
    outputs:
    
      versn: ${{ steps.versnid.outputs.versn }}
      
    steps:
      - uses: actions/checkout@v2
        
      - id: versnid
        run: |
          echo setting release version!!
          input='${{ github.workspace }}/versionnew.txt'
          echo "${{ github.run_number }}" >> versionnew.tx
          newversion=$(cat versionnew.tx)
          echo $newversion
          echo "::set-output name=versn::$newversion"
