name:  Build_POC

on: 
  workflow_dispatch:
  
jobs:

  Pre-Release:
  
    name: Versioning
    runs-on: ubuntu-latest
    
      
    steps:
      - uses: actions/checkout@v2
        
      - id: versnid
        run: |
          echo setting release version!!
          echo "${{ github.run_number }}" >> version.cfg
          newversion=$(cat version.cfg | tr -d "[:space:]")
          echo $newversion
          name:  CPQ_Apps_Build


          
  Build:
  
       needs: Pre-Release
       runs-on: windows-latest
       steps:
         - name: Checkout
           uses: actions/checkout@v3
         
         - name: Setup DotNet
           uses: actions/setup-dotnet@v2
           
         - name: dotnetBuild
           shell : pwsh
           run: |
              echo "Dotnet version to be used by default"
              dotnet --version
              dotnet --list-sdks
              dotnet --info
              dotnet new globaljson --sdk-version 3.1.405
              
              echo "Dotnet version to be used after setting to specific version"
              dotnet --version
               
           
             
        

          
